services:

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: sofka-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - sofka-network

  db-clientes:
    image: postgres:15-alpine
    container_name: sofka-db-clientes
    environment:
      POSTGRES_DB: db_clientes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - clientes-data:/var/lib/postgresql/data
      - ./BaseDatos.sql:/docker-entrypoint-initdb.d/BaseDatos.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_clientes"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sofka-network

  db-cuentas:
    image: postgres:15-alpine
    container_name: sofka-db-cuentas
    environment:
      POSTGRES_DB: db_cuentas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - cuentas-data:/var/lib/postgresql/data
      - ./BaseDatos.sql:/docker-entrypoint-initdb.d/BaseDatos.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_cuentas"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sofka-network

  ms-clientes:
    build:
      context: ./ms-clientes
      dockerfile: Dockerfile
    container_name: sofka-ms-clientes
    ports:
      - "8081:8081"
    environment:
      DB_HOST: db-clientes
      DB_PORT: 5432
      DB_NAME: db_clientes
      DB_USER: postgres
      DB_PASS: postgres
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASS: guest
    depends_on:
      db-clientes:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - sofka-network
    restart: on-failure

  ms-cuentas:
    build:
      context: ./ms-cuentas
      dockerfile: Dockerfile
    container_name: sofka-ms-cuentas
    ports:
      - "8082:8082"
    environment:
      DB_HOST: db-cuentas
      DB_PORT: 5432
      DB_NAME: db_cuentas
      DB_USER: postgres
      DB_PASS: postgres
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASS: guest
    depends_on:
      db-cuentas:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - sofka-network
    restart: on-failure

volumes:
  clientes-data:
  cuentas-data:

networks:
  sofka-network:
    driver: bridge
